### ISSUE TITLE
0.3.4 - Method Parameter Exception: the following parameters must be supplied for resolvePackageVersionId()

### ISSUE THREAD

**Issue by MarcDBehr** [ImJohnMDaniel/sfdx-toolbox-package-utils#3]
When using version 0.3.4 on a windoze system (a co-worker), getting the following error:

```
$ sfdx toolbox:package:dependencies:install --noprecheck -u ML --json
{
  "status": 1,
  "name": "SfdxError",
  "message": "Method Parameter Exception: the following parameters must be supplied for resolvePackageVersionId() -- thisOrg",
  "exitCode": 1,
  "commandName": "Install",
  "stack": "SfdxError: Method Parameter Exception: the following parameters must be supplied for resolvePackageVersionId() -- thisOrg\n    at Object.<anonymous> (C:\\Users\\ML\\AppData\\Local\\sfdx\\node_modules\\@dx-cli-toolbox\\sfdx-toolbox-package-utils\\lib\\shared\\devhubService.js:54:19)\n    at Generator.next (<anonymous>)\n    at C:\\Users\\ML\\AppData\\Local\\sfdx\\node_modules\\@dx-cli-toolbox\\sfdx-toolbox-package-utils\\lib\\shared\\devhubService.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (C:\\Users\\ML\\AppData\\Local\\sfdx\\node_modules\\@dx-cli-toolbox\\sfdx-toolbox-package-utils\\lib\\shared\\devhubService.js:4:12)\n    at Object.resolvePackageVersionId (C:\\Users\\ML\\AppData\\Local\\sfdx\\node_modules\\@dx-cli-toolbox\\sfdx-toolbox-package-utils\\lib\\shared\\devhubService.js:36:12)\n    at Install.<anonymous> (C:\\Users\\ML\\AppData\\Local\\sfdx\\node_modules\\@dx-cli-toolbox\\sfdx-toolbox-package-utils\\lib\\commands\\toolbox\\package\\dependencies\\install.js:90:84)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\ML\\AppData\\Local\\sfdx\\node_modules\\@dx-cli-toolbox\\sfdx-toolbox-package-utils\\lib\\commands\\toolbox\\package\\dependencies\\install.js:5:58)",
  "warnings": []
}
```

After downgrading to version 0.3.3, the exact same command works

**Comment by ImJohnMDaniel** [comment]
G'day @MarcDBehr -- Would you mind sharing your sfdx-project.json with me?

**Comment by MarcDBehr** [comment]
Is there a way that I can send it to you offline?

**Comment by ImJohnMDaniel** [comment]
Yeah, I saw your earlier message on Trailblaziers.  I left you my email address.  I am also on [Good Day, Sir! Slack](https://www.gooddaysirpodcast.com/community) and is probably a good place to reach me.
